### ISSUE TITLE
Some snippets are not highlighted correctly ; mixed language problem?

### ISSUE THREAD

**Issue by emicklei** [soypat/go-presentx#3]
I have a presentation (see https://github.com/emicklei/talks/tree/master/2014/devfest) that has a page explaining the difference between Java and Go.  Below you see the content of that page.  
Rendering this presentation show dark characters on a black background ; the code is not visible.

```
* Interfaces

An interface is a set of methods.
In Java:

	interface Switch {
	    void open();
	    void close();
	}

In Go:

	type OpenCloser interface {
	    Open()
	    Close()
	}

- Java interfaces are satisfied *explicitly*.
- Go interfaces are satisfied *implicitly*.
```

**Comment by soypat** [comment]
Hey! Thanks for  letting me know of this bug. As the tool stands, it does not apply highlighting to loose code. I believe there was a reason for this (the highlighter selector in slides.tmpl was highly sensitive to miniscule changes). I suggest you bring in the code from a file so that the template engine correctly marks it as highlightable! If you'd prefer applying a fix then that is welcome too.
